REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.leox
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\LeoxFile
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\LeoxFile\DefaultIcon
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\LeoxFile\shell
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\LeoxFile\shell\open
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\LeoxFile\shell\open\command
