<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet ekr_test?>
<leo_file>
<leo_header file_format="2" tnodes="0" max_tnode_index="0" clone_windows="0"/>
<globals body_outline_ratio="0.292267365662">
	<global_window_position top="10" left="10" height="773" width="1526"/>
	<global_log_window_position top="0" left="0" height="0" width="0"/>
</globals>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="AGP.20250415230112.1"><vh>Codenew</vh>
<v t="AGP.20250415230112.2"><vh>Core classes...</vh>
<v t="AGP.20250415230112.3"
marks="AGP.20250415230112.9,"><vh>@thin leo.py </vh></v>
<v t="AGP.20250415230112.14"
marks="AGP.20250415230112.19,AGP.20250415230112.28,AGP.20250415230112.39,"><vh>@thin leoApp.py</vh></v>
<v t="AGP.20250415230112.41"
marks="AGP.20250415230112.94,AGP.20250415230112.241,"><vh>@thin leoAtFile.py</vh></v>
<v t="AGP.20250415230112.299"
marks="AGP.20250415230112.300,"><vh>@thin leoLang.py</vh></v>
<v t="AGP.20250415230112.301"
marks="AGP.20250415230112.308,AGP.20250415230112.309,AGP.20250415230112.310,AGP.20250415230112.320,AGP.20250417084753,AGP.20250421213738,AGP.20250421214239,"><vh>@thin leoColor.py</vh></v>
<v t="AGP.20250415230112.329"
marks="AGP.20250415230112.344,AGP.20250415230112.625,AGP.20250415230112.687,AGP.20250415230112.707,AGP.20250415230112.708,AGP.20250415230112.709,"><vh>@thin leoCommands.py</vh></v>
<v t="AGP.20250415230112.718"
marks="AGP.20250415230112.726,AGP.20250415230112.801,"><vh>@thin leoConfig.py</vh></v>
<v t="AGP.20250415230112.813"
marks="AGP.20250415230112.915,AGP.20250415230112.920,AGP.20250415230112.971,AGP.20250415230112.1184,AGP.20250415230112.1187,AGP.20250415230112.1189,"><vh>@thin leoEditCommands.py</vh></v>
<v t="AGP.20250415230112.1210"
marks="AGP.20250415230112.1242,AGP.20250415230112.1256,AGP.20250415230112.1292,AGP.20250415230112.1298,AGP.20250415230112.1361,"><vh>@thin leoFileCommands.py</vh></v>
<v t="AGP.20250415230112.1384"
marks="AGP.20250415230112.1389,AGP.20250415230112.1390,AGP.20250415230112.1391,AGP.20250415230112.1403,AGP.20250415230112.1404,AGP.20250415230112.1490,AGP.20250415230112.1516,AGP.20250415230112.1711,"><vh>@thin leoGlobals.py</vh></v>
<v t="AGP.20250415230112.1733"><vh>@thin leoImport.py</vh></v>
<v t="AGP.20250415230112.1893"
marks="AGP.20250415230112.1904,AGP.20250415230112.1943,AGP.20250415230112.2025,AGP.20250415230112.2076,"><vh>@thin leoKeys.py</vh></v>
<v t="AGP.20250415230112.2096"
marks="AGP.20250415230112.2115,AGP.20250415230112.2173,AGP.20250415230112.2174,AGP.20250415230112.2177,AGP.20250415230112.2179,AGP.20250415230112.2216,AGP.20250415230112.2259,AGP.20250415230112.2260,AGP.20250415230112.2284,AGP.20250415230112.2286,AGP.20250415230112.2288,AGP.20250415230112.2289,AGP.20250415230112.2290,AGP.20250415230112.2319,AGP.20250415230112.2320,"><vh>@thin leoNodes.py</vh></v>
<v t="AGP.20250415230112.2321"><vh>@thin leoPlugins.py</vh></v>
<v t="AGP.20250415230112.2343"><vh>thin leoPymacs.py</vh>
<v t="AGP.20250415230112.2344"><vh>&lt;&lt; docstring &gt;&gt;</vh></v>
<v t="AGP.20250415230112.2345"><vh>dump</vh></v>
<v t="AGP.20250415230112.2346"><vh>getters</vh></v>
<v t="AGP.20250415230112.2347"><vh>hello</vh></v>
<v t="AGP.20250415230112.2348"><vh>init</vh></v>
<v t="AGP.20250415230112.2349"><vh>open</vh></v>
<v t="AGP.20250415230112.2350"><vh>run-script</vh></v>
</v>
<v t="AGP.20250415230112.2351"
marks="AGP.20250415230112.2534,"><vh>@thin leoTangle.py</vh></v>
<v t="AGP.20250415230112.2536" annotate="285808000000616e6e6f7461746571007d71017471022e"><vh>@thin leoTest.py</vh></v>
<v t="AGP.20250415230112.2642"><vh>@thin leoUndo.py</vh></v>
</v>
<v t="AGP.20250415230112.2737"><vh>Gui Base classes</vh>
<v t="AGP.20250415230112.2738"><vh>&lt;&lt; about gui classes and gui plugins &gt;&gt;</vh></v>
<v t="AGP.20250415230112.2739"
marks="AGP.20250415230112.2743,AGP.20250415230112.2774,AGP.20250415230112.2775,AGP.20250415230112.2776,AGP.20250415230112.2778,AGP.20250415230112.2785,AGP.20250415230112.2791,"><vh>@thin leoFind.py</vh></v>
<v t="AGP.20250415230112.2797"><vh>@thin leoFrame.py</vh></v>
<v t="AGP.20250415230112.2925"><vh>@thin leoGui.py</vh></v>
<v t="AGP.20250415230112.2969"
marks="AGP.20250415230112.2987,AGP.20250415230112.3005,AGP.20250415230112.3007,AGP.20250415230112.3058,"><vh>@thin leoMenu.py</vh></v>
</v>
<v t="AGP.20250415230112.3076"><vh>Gui Tkinter classes</vh>
<v t="AGP.20250415230112.3077"><vh>thin leoTkinterKeys.py</vh></v>
<v t="AGP.20250415230112.3078"><vh>thin leoTkinterComparePanel.py</vh>
<v t="AGP.20250415230112.3079"><vh>Birth...</vh>
<v t="AGP.20250415230112.3080"><vh> tkinterComparePanel.__init__</vh>
<v t="AGP.20250415230112.3081"><vh>&lt;&lt; init tkinter compare ivars &gt;&gt;</vh></v>
</v>
<v t="AGP.20250415230112.3082"><vh>finishCreate (tkComparePanel)</vh></v>
<v t="AGP.20250415230112.3083"><vh>createFrame (tkComparePanel)</vh>
<v t="AGP.20250415230112.3084"><vh>&lt;&lt; create the organizer frames &gt;&gt;</vh></v>
<v t="AGP.20250415230112.3085"><vh>&lt;&lt; create the browser rows &gt;&gt;</vh></v>
<v t="AGP.20250415230112.3086"><vh>&lt;&lt; create the extension row &gt;&gt;</vh></v>
<v t="AGP.20250415230112.3087"><vh>&lt;&lt; create the whitespace options frame &gt;&gt;</vh></v>
<v t="AGP.20250415230112.3088"><vh>&lt;&lt; create the print options frame &gt;&gt;</vh></v>
<v t="AGP.20250415230112.3089"><vh>&lt;&lt; create the compare buttons &gt;&gt;</vh></v>
</v>
<v t="AGP.20250415230112.3090"><vh>setIvarsFromWidgets</vh></v>
</v>
<v t="AGP.20250415230112.3091"><vh>bringToFront</vh></v>
<v t="AGP.20250415230112.3092"><vh>browser</vh></v>
<v t="AGP.20250415230112.3093"><vh>Event handlers...</vh>
<v t="AGP.20250415230112.3094"><vh>onBrowse...</vh></v>
<v t="AGP.20250415230112.3095"><vh>onClose</vh></v>
<v t="AGP.20250415230112.3096"><vh>onCompare...</vh></v>
<v t="AGP.20250415230112.3097"><vh>onPrintMatchedLines</vh></v>
</v>
</v>
<v t="AGP.20250415230112.3098"><vh>thin leoTkinterFind.py</vh>
<v t="AGP.20250415230112.3099"><vh>class underlinedTkButton</vh>
<v t="AGP.20250415230112.3100"><vh>__init__</vh>
<v t="AGP.20250415230112.3101"><vh>&lt;&lt; set self.hotKey if '&amp;' is in the string &gt;&gt;</vh></v>
</v>
<v t="AGP.20250415230112.3102"><vh>bindHotKey</vh></v>
<v t="AGP.20250415230112.3103"><vh>buttonCallback</vh></v>
</v>
<v t="AGP.20250415230112.3104"><vh>class leoTkinterFind</vh>
<v t="AGP.20250415230112.3105"><vh>Birth &amp; death</vh>
<v t="AGP.20250415230112.3106"><vh>__init__</vh>
<v t="AGP.20250415230112.3107"><vh>&lt;&lt; create the tkinter intVars &gt;&gt;</vh></v>
</v>
<v t="AGP.20250415230112.3108"><vh>destroySelf</vh></v>
<v t="AGP.20250415230112.3109"><vh>find.createFrame</vh>
<v t="AGP.20250415230112.3110"><vh>&lt;&lt; Create the Find and Change panes &gt;&gt;</vh>
<v t="AGP.20250415230112.3111"><vh>&lt;&lt; Bind Tab and control-tab &gt;&gt;</vh></v>
</v>
<v t="AGP.20250415230112.3112"><vh>&lt;&lt; Create four columns of radio and checkboxes &gt;&gt;</vh></v>
<v t="AGP.20250415230112.3113"><vh>&lt;&lt; Create two rows of buttons &gt;&gt;</vh></v>
</v>
<v t="AGP.20250415230112.3114"><vh>find.createBindings</vh></v>
<v t="AGP.20250415230112.3115"><vh>find.init</vh>
<v t="AGP.20250415230112.3116"><vh>&lt;&lt; set find/change widgets &gt;&gt;</vh></v>
<v t="AGP.20250415230112.3117"><vh>&lt;&lt; set radio buttons from ivars &gt;&gt;</vh></v>
</v>
</v>
<v t="AGP.20250415230112.3118"><vh>find.update_ivars</vh></v>
<v t="AGP.20250415230112.3119"><vh>tkFind.adjust_find_text</vh></v>
<v t="AGP.20250415230112.3120"><vh>onCloseWindow</vh></v>
<v t="AGP.20250415230112.3121"><vh>dismiss</vh></v>
<v t="AGP.20250415230112.3122"><vh>bringToFront</vh></v>
<v t="AGP.20250415230112.3123"><vh>selectAllFindText</vh></v>
<v t="AGP.20250415230112.3124"><vh>Tkinter wrappers (leoTkinterFind)</vh></v>
</v>
</v>
<v t="AGP.20250415230112.3125"><vh>@thin leoTkinterDialog.py</vh></v>
<v t="AGP.20250415230112.3172"
marks="AGP.20250415230112.3179,AGP.20250415230112.3211,AGP.20250415230112.3218,AGP.20250415230112.3226,AGP.20250415230112.3228,AGP.20250415230112.3234,AGP.20250415230112.3235,AGP.20250415230112.3246,AGP.20250415230112.3273,AGP.20250415230112.3274,AGP.20250415230112.3291,AGP.20250415230112.3292,AGP.20250415230112.3319,AGP.20250415230112.3327,AGP.20250415230112.3336,AGP.20250415230112.3338,AGP.20250415230112.3341,AGP.20250415230112.3342,AGP.20250415230112.3344,AGP.20250415230112.3357,AGP.20250415230112.3374,AGP.20250415230112.3443,AGP.20250415230112.3454,AGP.20250415230112.3455,AGP.20250415230112.3462,"><vh>@thin leoTkinterFrame.py</vh></v>
<v t="AGP.20250415230112.3483"
marks="AGP.20250415230112.3487,AGP.20250415230112.3499,AGP.20250415230112.3525,"><vh>@thin leoTkinterGui.py</vh></v>
<v t="AGP.20250415230112.3560"
marks="AGP.20250415230112.3565,AGP.20250415230112.3576,AGP.20250415230112.3580,"><vh>@thin leoTkinterMenu.py</vh></v>
<v t="AGP.20250415230112.3586"
marks="AGP.20250415230112.3593,AGP.20250415230112.3594,AGP.20250415230112.3600,AGP.20250415230112.3603,AGP.20250415230112.3615,AGP.20250415230112.3626,AGP.20250415230112.3640,AGP.20250415230112.3642,AGP.20250415230112.3645,AGP.20250415230112.3653,AGP.20250415230112.3683,AGP.20250415230112.3697,AGP.20250415230112.3710,"><vh>@thin leoTkinterTree.py</vh></v>
</v>
</v>
<v t="AGP.20251113192637" a="E"><vh>windows files reg</vh>
<v t="AGP.20251113192637.1" tnodeList="AGP.20251113192637.1"><vh>@nosent ..\regleox_console.bat</vh></v>
<v t="AGP.20251113192710" tnodeList="AGP.20251113192710"><vh>@nosent ..\regleox_window.bat</vh></v>
<v t="AGP.20251113192847" a="TV" tnodeList="AGP.20251113192847"><vh>@nosent ..\unregleox.bat</vh></v>
</v>
</vnodes>
<tnodes>
<t tx="AGP.20250415230112.1">@tabwidth -4
@pagewidth 80

@ This section contains all the source code of leo.py.

Leo's code uses the following conventions throughout:

c:  a commander
ch: a character
d:  a dialog or a dict.
g:  the leoGlobal module.
i, j, k: indices into a string
p:  a position.
s:  a string
t:  a tnode or a text widget.
u:  an undoer
v:  a vnode
z:  a local temp.</t>
<t tx="AGP.20250415230112.2"></t>
<t tx="AGP.20250415230112.2343">@first # -*- coding: utf-8 -*-

&lt;&lt; docstring&gt;&gt;

@language python
@tabwidth -4

# As in leo.py we must be very careful about imports.
g = None # set by init: do *not* import it here!
inited = False

@others</t>
<t tx="AGP.20250415230112.2344">'''A module to allow the Pymacs bridge to access Leo data.

All code in this module must be called *from* Emacs:
calling Pymacs.lisp in other situations will hang Leo.

Emacs code initiallizes this module with::
    
    (pymacs-eval "sys.path.append('c:\\prog\\tigris-cvs\\leo\\src')")
    (setq leo (pymacs-load "leoPymacs"))

'''
</t>
<t tx="AGP.20250415230112.2345">def dump (anObject):
    
    init()
    
    return str(g.toEncodedString(repr(anObject),encoding='ascii'))
</t>
<t tx="AGP.20250415230112.2346">def get_app ():
    '''Scripts can use g.app.scriptDict for communication with pymacs.'''
    init()
    return g.app
    
def get_g():
    init()
    return g
    
def script_result():
    init()
    return g.app.scriptResult</t>
<t tx="AGP.20250415230112.2347">def hello():

    init()
    return 'Hello from Leo.  g.app: %s' % g.app</t>
<t tx="AGP.20250415230112.2348">def init ():
    
    global inited

    if inited:
        return
    else:
        inited = True
    
    # Create the dummy app
    import leo 
    leo.run(pymacs=True)
    
    import leoGlobals
    global g ; g = leoGlobals

    # These traces show up in the pymacs buffer.
    g.trace('app',g.app)
    g.trace('gui',g.app.gui)
</t>
<t tx="AGP.20250415230112.2349">def open (fileName=None):
    
    init()
    
    if g.app.unitTesting:
        return
    
    if not fileName:
        g.es_print('leoPymacs.open: no file name')
        return None

    # openWithFileName checks to see if the file is already open.
    ok, frame = g.openWithFileName(
        fileName,
        old_c=None,
        enableLog=False,
        readAtFileNodesFlag=True)

    c = ok and frame.c or None
    if c:
        g.es_print('leoPymacs.open: %s' % c)
    else:
        g.es_print('leoPymacs.open: Can not open %s' % fileName)

    return c</t>
<t tx="AGP.20250415230112.2350">def run_script(c,script,p=None):
    
    # It is possible to use script=None, in which case p must be defined.
    
    init()
    
    if c is None:
        c,frame = g.app.newLeoCommanderAndFrame(fileName='dummy script file')
            
    g.app.scriptResult = None

    c.executeScript(
        event=None,
        p=p,
        script=script,
        useSelectedText=False,
        define_g=True,
        define_name='__main__',
        silent=True,  # Don't write to the log.
    )
    
    # g.trace('script returns: ',repr(g.app.scriptResult))
    return g.app.scriptResult</t>
<t tx="AGP.20250415230112.2737">&lt;&lt; about gui classes and gui plugins &gt;&gt;
</t>
<t tx="AGP.20250415230112.2738">@nocolor

The following are notes for anyone who is interested in writing alternate gui's for Leo.

Rule 1: Leo's core is (or should be) free of gui-specific code.

Core code calls 'gui wrapper methods' defined by gui-specific classes.  The base classes for these gui-specific classes are in the node Code--&gt;Gui Base classes.

Rule 2: Gui-specific code should be localized.  

The @file nodes contained in the node 'Code--&gt;Gui Tkinter classes' in leoPy.leo contain all of Leo's Tkinter-specific code.  Gui plugins would typically put all similar code in a single file.

Rule 3: Gui-specific code can call gui methods directly.

There are no restrictions about the code in the gui-specific classes.

Rule 4:  Gui-specific classes must implement the 'gui wrapper methods' specified in the gui base classes.

This is the way that gui-specific classes provide gui-specific services to Leo's core.

The alternative would be to implement all gui-specific commands directly in the gui-specific code.  But this would be much more work than needed.  For example, only a few gui-specific wrappers are needed to implement all commands that deal with body text.  Implementing each of these commands 'from scratch' would duplicate a lot of code unnecessarily.

Using the gui wrapper methods is a bit messy for two reasons:

1.  It requires defining enough wrappers (both in the base gui classes and subclasses) so that all gui-specific services needed by Leo's core are available.   Adding a wrapper to a gui base class involves adding it to all gui-specific subclasses.  It's easy to forget to add a wrapper.  The gui base class defines all wrappers as a function that just calls oops().  This prints a warning that the wrapper should be defined in a subclass.

2. The original wrappers assumed Tkinter-like indices.  Wrappers that were defined later assume Python indices (see Rule 5 below).   The newer style wrappers that use Python indices have 'Python' in their name.   Having two sets of wrappers is one of the ugliest features of the present code.  I find it hard to remember which wrappers exist and what exactly they do :-)

Rule 5:  Leo's core should use Python indices, not gui-specific indices.

Leo's core mostly follows this rule: there may be a few exceptions.

A Python index is an int that runs from 0 (beginning of text) to len(s) (end of text s).  That is, there are exactly len(s) + 1 valid indices.  In contrast, Tkinter indices run from "1.0" to "x.y" where text s has x lines and where the length of the last line is y-1. 

Two (recently written) functions in leoGlobals.py support conversions from Python indices to the row/column indices used by Tkinter.

- g.convertPythonIndexToRowCol converts a Python index to a row/column index used by Tkinter.
- g.convertRowColToPythonIndex does the reverse.

Important:  the first Tkinter index is '1.0', not '0.0', but the row returned by g.convertPythonIndexToRowCol is zero based, so the code that actually creates Tkinter indices from row/col must add 1 to the row.  Similar remarks apply when going in the reverse direction.
</t>
<t tx="AGP.20250415230112.3076"></t>
<t tx="AGP.20250415230112.3077">"""Tkinter keystroke handling for Leo."""

@language python
@tabwidth -4
@pagewidth 80

import leoGlobals as g
</t>
<t tx="AGP.20250415230112.3078">"""Leo's base compare class."""

@language python
@tabwidth -4
@pagewidth 80

import leoGlobals as g
import leoCompare
import leoTkinterDialog
import Tkinter as Tk
import tkFileDialog

class leoTkinterComparePanel (leoCompare.leoCompare,leoTkinterDialog.leoTkinterDialog):
    
    """A class that creates Leo's compare panel."""

    @others
</t>
<t tx="AGP.20250415230112.3079"></t>
<t tx="AGP.20250415230112.3080">def __init__ (self,c):
    
    # Init the base class.
    leoCompare.leoCompare.__init__ (self,c)
    leoTkinterDialog.leoTkinterDialog.__init__(self,c,"Compare files and directories",resizeable=False)

    if g.app.unitTesting: return

    self.c = c

    &lt;&lt; init tkinter compare ivars &gt;&gt;
    
    # These ivars are set from Entry widgets.
    self.limitCount = 0
    self.limitToExtension = None
    
    # The default file name in the "output file name" browsers.
    self.defaultOutputFileName = "CompareResults.txt"
    
    self.createTopFrame()
    self.createFrame()
</t>
<t tx="AGP.20250415230112.3081"># Ivars pointing to Tk elements.
self.browseEntries = []
self.extensionEntry = None
self.countEntry = None
self.printButtons = []
    
# No corresponding ivar in the leoCompare class.
self.useOutputFileVar = Tk.IntVar()

# These all correspond to ivars in leoCompare
self.appendOutputVar             = Tk.IntVar()

self.ignoreBlankLinesVar         = Tk.IntVar()
self.ignoreFirstLine1Var         = Tk.IntVar()
self.ignoreFirstLine2Var         = Tk.IntVar()
self.ignoreInteriorWhitespaceVar = Tk.IntVar()
self.ignoreLeadingWhitespaceVar  = Tk.IntVar()
self.ignoreSentinelLinesVar      = Tk.IntVar()

self.limitToExtensionVar         = Tk.IntVar()
self.makeWhitespaceVisibleVar    = Tk.IntVar()

self.printBothMatchesVar         = Tk.IntVar()
self.printMatchesVar             = Tk.IntVar()
self.printMismatchesVar          = Tk.IntVar()
self.printTrailingMismatchesVar  = Tk.IntVar()
self.stopAfterMismatchVar        = Tk.IntVar()
</t>
<t tx="AGP.20250415230112.3082"># Initialize ivars from config parameters.

def finishCreate (self):
    
    c = self.c
    
    # File names.
    for i,option in (
        (0,"compare_file_1"),
        (1,"compare_file_2"),
        (2,"output_file") ):
            
        name = c.config.getString(option)
        if name and len(name) &gt; 0:
            e = self.browseEntries[i]
            e.delete(0,"end")
            e.insert(0,name)
            
    name = c.config.getString("output_file")
    b = g.choose(name and len(name) &gt; 0,1,0)
    self.useOutputFileVar.set(b)

    # File options.
    b = c.config.getBool("ignore_first_line_of_file_1")
    if b == None: b = 0
    self.ignoreFirstLine1Var.set(b)
    
    b = c.config.getBool("ignore_first_line_of_file_2")
    if b == None: b = 0
    self.ignoreFirstLine2Var.set(b)
    
    b = c.config.getBool("append_output_to_output_file")
    if b == None: b = 0
    self.appendOutputVar.set(b)

    ext = c.config.getString("limit_directory_search_extension")
    b = ext and len(ext) &gt; 0
    b = g.choose(b and b != 0,1,0)
    self.limitToExtensionVar.set(b)
    if b:
        e = self.extensionEntry
        e.delete(0,"end")
        e.insert(0,ext)
        
    # Print options.
    b = c.config.getBool("print_both_lines_for_matches")
    if b == None: b = 0
    self.printBothMatchesVar.set(b)
    
    b = c.config.getBool("print_matching_lines")
    if b == None: b = 0
    self.printMatchesVar.set(b)
    
    b = c.config.getBool("print_mismatching_lines")
    if b == None: b = 0
    self.printMismatchesVar.set(b)
    
    b = c.config.getBool("print_trailing_lines")
    if b == None: b = 0
    self.printTrailingMismatchesVar.set(b)
    
    n = c.config.getInt("limit_count")
    b = n and n &gt; 0
    b = g.choose(b and b != 0,1,0)
    self.stopAfterMismatchVar.set(b)
    if b:
        e = self.countEntry
        e.delete(0,"end")
        e.insert(0,str(n))

    # bool options...
    for option,var,default in (
        # Whitespace options.
        ("ignore_blank_lines",self.ignoreBlankLinesVar,1),
        ("ignore_interior_whitespace",self.ignoreInteriorWhitespaceVar,0),
        ("ignore_leading_whitespace",self.ignoreLeadingWhitespaceVar,0),
        ("ignore_sentinel_lines",self.ignoreSentinelLinesVar,0),
        ("make_whitespace_visible", self.makeWhitespaceVisibleVar,0),
    ):
        b = c.config.getBool(option)
        if b is None: b = default
        var.set(b)
    
    if 0: # old code
        b = c.config.getBool("ignore_blank_lines")
        if b == None: b = 1 # unusual default.
        self.ignoreBlankLinesVar.set(b)
        
        b = c.config.getBool("ignore_interior_whitespace")
        if b == None: b = 0
        self.ignoreInteriorWhitespaceVar.set(b)
        
        b = c.config.getBool("ignore_leading_whitespace")
        if b == None: b = 0
        self.ignoreLeadingWhitespaceVar.set(b)
        
        b = c.config.getBool("ignore_sentinel_lines")
        if b == None: b = 0
        self.ignoreSentinelLinesVar.set(b)
        
        b = c.config.getBool("make_whitespace_visible")
        if b == None: b = 0
        self.makeWhitespaceVisibleVar.set(b)
</t>
<t tx="AGP.20250415230112.3083">def createFrame (self):

    gui = g.app.gui ; top = self.top

    &lt;&lt; create the organizer frames &gt;&gt;
    &lt;&lt; create the browser rows &gt;&gt;
    &lt;&lt; create the extension row &gt;&gt;
    &lt;&lt; create the whitespace options frame &gt;&gt;
    &lt;&lt; create the print options frame &gt;&gt;
    &lt;&lt; create the compare buttons &gt;&gt;

    gui.center_dialog(top) # Do this _after_ building the dialog!
    self.finishCreate()
    top.protocol("WM_DELETE_WINDOW", self.onClose)
</t>
<t tx="AGP.20250415230112.3084">outer = Tk.Frame(self.frame, bd=2,relief="groove")
outer.pack(pady=4)

row1 = Tk.Frame(outer)
row1.pack(pady=4)

row2 = Tk.Frame(outer)
row2.pack(pady=4)

row3 = Tk.Frame(outer)
row3.pack(pady=4)

row4 = Tk.Frame(outer)
row4.pack(pady=4,expand=1,fill="x") # for left justification.

options = Tk.Frame(outer)
options.pack(pady=4)

ws = Tk.Frame(options)
ws.pack(side="left",padx=4)

pr = Tk.Frame(options)
pr.pack(side="right",padx=4)

lower = Tk.Frame(outer)
lower.pack(pady=6)
</t>
<t tx="AGP.20250415230112.3085">for row,text,text2,command,var in (
    (row1,"Compare path 1:","Ignore first line",self.onBrowse1,self.ignoreFirstLine1Var),
    (row2,"Compare path 2:","Ignore first line",self.onBrowse2,self.ignoreFirstLine2Var),
    (row3,"Output file:",   "Use output file",  self.onBrowse3,self.useOutputFileVar) ):

    lab = Tk.Label(row,anchor="e",text=text,width=13)
    lab.pack(side="left",padx=4)
    
    e = Tk.Entry(row)
    e.pack(side="left",padx=2)
    self.browseEntries.append(e)
    
    b = Tk.Button(row,text="browse...",command=command)
    b.pack(side="left",padx=6)

    b = Tk.Checkbutton(row,text=text2,anchor="w",variable=var,width=15)
    b.pack(side="left")
</t>
<t tx="AGP.20250415230112.3086">b = Tk.Checkbutton(row4,anchor="w",var=self.limitToExtensionVar,
    text="Limit directory compares to type:")
b.pack(side="left",padx=4)

self.extensionEntry = e = Tk.Entry(row4,width=6)
e.pack(side="left",padx=2)

b = Tk.Checkbutton(row4,anchor="w",var=self.appendOutputVar,
    text="Append output to output file")
b.pack(side="left",padx=4)
</t>
<t tx="AGP.20250415230112.3087">w,f = gui.create_labeled_frame(ws,caption="Whitespace options",relief="groove")
    
for text,var in (
    ("Ignore Leo sentinel lines", self.ignoreSentinelLinesVar),
    ("Ignore blank lines",        self.ignoreBlankLinesVar),
    ("Ignore leading whitespace", self.ignoreLeadingWhitespaceVar),
    ("Ignore interior whitespace",self.ignoreInteriorWhitespaceVar),
    ("Make whitespace visible",   self.makeWhitespaceVisibleVar) ):
    
    b = Tk.Checkbutton(f,text=text,variable=var)
    b.pack(side="top",anchor="w")
    
spacer = Tk.Frame(f)
spacer.pack(padx="1i")
</t>
<t tx="AGP.20250415230112.3088">w,f = gui.create_labeled_frame(pr,caption="Print options",relief="groove")

row = Tk.Frame(f)
row.pack(expand=1,fill="x")

b = Tk.Checkbutton(row,text="Stop after",variable=self.stopAfterMismatchVar)
b.pack(side="left",anchor="w")

self.countEntry = e = Tk.Entry(row,width=4)
e.pack(side="left",padx=2)
e.insert(01,"1")

lab = Tk.Label(row,text="mismatches")
lab.pack(side="left",padx=2)

for padx,text,var in (    
    (0,  "Print matched lines",           self.printMatchesVar),
    (20, "Show both matching lines",      self.printBothMatchesVar),
    (0,  "Print mismatched lines",        self.printMismatchesVar),
    (0,  "Print unmatched trailing lines",self.printTrailingMismatchesVar) ):
    
    b = Tk.Checkbutton(f,text=text,variable=var)
    b.pack(side="top",anchor="w",padx=padx)
    self.printButtons.append(b)
    
# To enable or disable the "Print both matching lines" button.
b = self.printButtons[0]
b.configure(command=self.onPrintMatchedLines)

spacer = Tk.Frame(f)
spacer.pack(padx="1i")
</t>
<t tx="AGP.20250415230112.3089">for text,command in (
    ("Compare files",      self.onCompareFiles),
    ("Compare directories",self.onCompareDirectories) ):
    
    b = Tk.Button(lower,text=text,command=command,width=18)
    b.pack(side="left",padx=6)
</t>
<t tx="AGP.20250415230112.3090">def setIvarsFromWidgets (self):

    # File paths: checks for valid file name.
    e = self.browseEntries[0]
    self.fileName1 = e.get()
    
    e = self.browseEntries[1]
    self.fileName2 = e.get()

    # Ignore first line settings.
    self.ignoreFirstLine1 = self.ignoreFirstLine1Var.get()
    self.ignoreFirstLine2 = self.ignoreFirstLine2Var.get()
    
    # Output file: checks for valid file name.
    if self.useOutputFileVar.get():
        e = self.browseEntries[2]
        name = e.get()
        if name != None and len(name) == 0:
            name = None
        self.outputFileName = name
    else:
        self.outputFileName = None

    # Extension settings.
    if self.limitToExtensionVar.get():
        self.limitToExtension = self.extensionEntry.get()
        if len(self.limitToExtension) == 0:
            self.limitToExtension = None
    else:
        self.limitToExtension = None
        
    self.appendOutput = self.appendOutputVar.get()
    
    # Whitespace options.
    self.ignoreBlankLines         = self.ignoreBlankLinesVar.get()
    self.ignoreInteriorWhitespace = self.ignoreInteriorWhitespaceVar.get()
    self.ignoreLeadingWhitespace  = self.ignoreLeadingWhitespaceVar.get()
    self.ignoreSentinelLines      = self.ignoreSentinelLinesVar.get()
    self.makeWhitespaceVisible    = self.makeWhitespaceVisibleVar.get()
    
    # Print options.
    self.printMatches            = self.printMatchesVar.get()
    self.printMismatches         = self.printMismatchesVar.get()
    self.printTrailingMismatches = self.printTrailingMismatchesVar.get()
    
    if self.printMatches:
        self.printBothMatches = self.printBothMatchesVar.get()
    else:
        self.printBothMatches = False
    
    if self.stopAfterMismatchVar.get():
        try:
            count = self.countEntry.get()
            self.limitCount = int(count)
        except: self.limitCount = 0
    else:
        self.limitCount = 0
</t>
<t tx="AGP.20250415230112.3091">def bringToFront(self):
    
    self.top.deiconify()
    self.top.lift()
</t>
<t tx="AGP.20250415230112.3092">def browser (self,n):
    
    types = [
        ("C/C++ files","*.c"),
        ("C/C++ files","*.cpp"),
        ("C/C++ files","*.h"),
        ("C/C++ files","*.hpp"),
        ("Java files","*.java"),
        ("Lua files", "*.lua"),
        ("Pascal files","*.pas"),
        ("Python files","*.py"),
        ("Text files","*.txt"),
        ("All files","*") ]

    fileName = tkFileDialog.askopenfilename(
        title="Choose compare file" + n,
        filetypes=types,
        defaultextension=".txt")
        
    if fileName and len(fileName) &gt; 0:
        # The dialog also warns about this, so this may never happen.
        if not g.os_path_exists(fileName):
            self.show("not found: " + fileName)
            fileName = None
    else: fileName = None
        
    return fileName
</t>
<t tx="AGP.20250415230112.3093"></t>
<t tx="AGP.20250415230112.3094">def onBrowse1 (self):
    
    fileName = self.browser("1")
    if fileName:
        e = self.browseEntries[0]
        e.delete(0,"end")
        e.insert(0,fileName)
    self.top.deiconify()
    
def onBrowse2 (self):
    
    fileName = self.browser("2")
    if fileName:
        e = self.browseEntries[1]
        e.delete(0,"end")
        e.insert(0,fileName)
    self.top.deiconify()
    
def onBrowse3 (self): # Get the name of the output file.

    fileName = tkFileDialog.asksaveasfilename(
        initialfile = self.defaultOutputFileName,
        title="Set output file",
        filetypes=[("Text files", "*.txt")],
        defaultextension=".txt")
        
    if fileName and len(fileName) &gt; 0:
        self.defaultOutputFileName = fileName
        self.useOutputFileVar.set(1) # The user will expect this.
        e = self.browseEntries[2]
        e.delete(0,"end")
        e.insert(0,fileName)
</t>
<t tx="AGP.20250415230112.3095">def onClose (self):
    
    self.top.withdraw()
</t>
<t tx="AGP.20250415230112.3096">def onCompareDirectories (self):

    self.setIvarsFromWidgets()
    self.compare_directories(self.fileName1,self.fileName2)

def onCompareFiles (self):

    self.setIvarsFromWidgets()
    self.compare_files(self.fileName1,self.fileName2)
</t>
<t tx="AGP.20250415230112.3097">def onPrintMatchedLines (self):
    
    v = self.printMatchesVar.get()
    b = self.printButtons[1]
    state = g.choose(v,"normal","disabled")
    b.configure(state=state)
</t>
<t tx="AGP.20250415230112.3098">@language python
@tabwidth -4
@pagewidth 80

import leoGlobals as g
import leoFind

import leoTkinterDialog
import Tkinter as Tk

@others
</t>
<t tx="AGP.20250415230112.3099">class underlinedTkButton:
    
    @others
</t>
<t tx="AGP.20250415230112.3100">def __init__(self,buttonType,parent_widget,**keywords):

    self.buttonType = buttonType
    self.parent_widget = parent_widget
    self.hotKey = None
    text = keywords['text']

    &lt;&lt; set self.hotKey if '&amp;' is in the string &gt;&gt;

    # Create the button...
    if self.hotKey:
        keywords['text'] = text
        keywords['underline'] = index

    if buttonType.lower() == "button":
        self.button = Tk.Button(parent_widget,keywords)
    elif buttonType.lower() == "check":
        self.button = Tk.Checkbutton(parent_widget,keywords)
    elif buttonType.lower() == "radio":
        self.button = Tk.Radiobutton(parent_widget,keywords)
    else:
        g.trace("bad buttonType")
    
    self.text = text # for traces
</t>
<t tx="AGP.20250415230112.3101">index = text.find('&amp;')

if index &gt; -1:

    if index == len(text)-1:
        # The word ends in an ampersand.  Ignore it; there is no hot key.
        text = text[:-1]
    else:
        self.hotKey = text [index + 1]
        text = text[:index] + text[index+1:]
</t>
<t tx="AGP.20250415230112.3102">def bindHotKey (self,widget):
    
    if self.hotKey:
        for key in (self.hotKey.lower(),self.hotKey.upper()):
            widget.bind("&lt;Alt-%s&gt;" % key,self.buttonCallback)
</t>
<t tx="AGP.20250415230112.3103"># The hot key has been hit.  Call the button's command.

def buttonCallback (self, event=None):

    # g.trace(self.text)
    self.button.invoke ()
    
    # See if this helps.
    return 'break'
</t>
<t tx="AGP.20250415230112.3104">class leoTkinterFind (leoFind.leoFind,leoTkinterDialog.leoTkinterDialog):

    """A class that implements Leo's tkinter find dialog."""

    @others
</t>
<t tx="AGP.20250415230112.3105"></t>
<t tx="AGP.20250415230112.3106">def __init__(self,c,resizeable=False,title=None,show=True):

    # g.trace("leoTkinterFind",c)
    
    # Init the base classes...
    leoFind.leoFind.__init__(self,c,title=title)
    leoTkinterDialog.leoTkinterDialog.__init__(self,c,self.title,resizeable,show=show)

    &lt;&lt; create the tkinter intVars &gt;&gt;
    
    # These are created later.
    self.find_ctrl = None
    self.change_ctrl = None 
    
    self.createTopFrame() # Create the outer tkinter dialog frame.
    self.createFrame()
    if self.top and not show:
        self.top.withdraw()
    self.init(c) # New in 4.3: init only once.
</t>
<t tx="AGP.20250415230112.3107">self.dict = {}

for key in self.intKeys:
    self.dict[key] = Tk.IntVar()

for key in self.newStringKeys:
    self.dict[key] = Tk.StringVar()
    
self.s_ctrl = Tk.Text() # Used by find.search()
</t>
<t tx="AGP.20250415230112.3108">def destroySelf (self):
    
    self.top.destroy()
</t>
<t tx="AGP.20250415230112.3109">def createFrame (self):
    
    # g.trace('legacy')

    # Create the find panel...
    outer = Tk.Frame(self.frame,relief="groove",bd=2)
    outer.pack(padx=2,pady=2)

    &lt;&lt; Create the Find and Change panes &gt;&gt;
    &lt;&lt; Create four columns of radio and checkboxes &gt;&gt;
    &lt;&lt; Create two rows of buttons &gt;&gt;

    if self.top: # self.top may not exist during unit testing.
        self.top.protocol("WM_DELETE_WINDOW", self.onCloseWindow)
</t>
<t tx="AGP.20250415230112.3110">fc = Tk.Frame(outer, bd="1m")
fc.pack(anchor="n", fill="x", expand=1)

# Removed unused height/width params: using fractions causes problems in some locales!
fpane = Tk.Frame(fc, bd=1)
cpane = Tk.Frame(fc, bd=1)

fpane.pack(anchor="n", expand=1, fill="x")
cpane.pack(anchor="s", expand=1, fill="x")

# Create the labels and text fields...
flab = Tk.Label(fpane, width=8, text="Find:")
clab = Tk.Label(cpane, width=8, text="Change:")

# Use bigger boxes for scripts.
self.find_ctrl   = ftxt = Tk.Text(fpane,bd=1,relief="groove",height=4,width=20)
self.change_ctrl = ctxt = Tk.Text(cpane,bd=1,relief="groove",height=4,width=20)

&lt;&lt; Bind Tab and control-tab &gt;&gt;

fBar = Tk.Scrollbar(fpane,name='findBar')
cBar = Tk.Scrollbar(cpane,name='changeBar')

# Add scrollbars.
for bar,txt in ((fBar,ftxt),(cBar,ctxt)):
    txt['yscrollcommand'] = bar.set
    bar['command'] = txt.yview
    bar.pack(side="right", fill="y")

flab.pack(side="left")
clab.pack(side="left")
ctxt.pack(side="right", expand=1, fill="both")
ftxt.pack(side="right", expand=1, fill="both")
</t>
<t tx="AGP.20250415230112.3111">def setFocus(w):
    c = self.c
    c.widgetWantsFocus(w)
    g.app.gui.setSelectionRange(w,"1.0","1.0")
    return "break"
    
def toFind(event,w=ftxt): return setFocus(w)
def toChange(event,w=ctxt): return setFocus(w)

def insertTab(w):
    data = g.app.gui.getSelectionRange(w)
    if data: start,end = data
    else: start = end = g.app.gui.getInsertPoint(w)
    g.app.gui.replaceSelectionRangeWithText(w,start,end,"\t")
    return "break"

def insertFindTab(event,w=ftxt): return insertTab(w)
def insertChangeTab(event,w=ctxt): return insertTab(w)

ftxt.bind("&lt;Tab&gt;",toChange)
ctxt.bind("&lt;Tab&gt;",toFind)
ftxt.bind("&lt;Control-Tab&gt;",insertFindTab)
ctxt.bind("&lt;Control-Tab&gt;",insertChangeTab)
</t>
<t tx="AGP.20250415230112.3112">columnsFrame = Tk.Frame(outer,relief="groove",bd=2)
columnsFrame.pack(anchor="e",expand=1,padx="7p",pady="2p") # Don't fill.

numberOfColumns = 4 # Number of columns
columns = [] ; radioLists = [] ; checkLists = []
for i in xrange(numberOfColumns):
    columns.append(Tk.Frame(columnsFrame,bd=1))
    radioLists.append([])
    checkLists.append([])

for i in xrange(numberOfColumns):
    columns[i].pack(side="left",padx="1p") # fill="y" Aligns to top. padx expands columns.
    
# HotKeys used for check/radio buttons:  a,b,c,e,h,i,l,m,n,o,p,r,s,t,w

radioLists[0] = [
    (self.dict["radio-find-type"],"P&amp;Lain Search","plain-search"),  
    (self.dict["radio-find-type"],"&amp;Pattern Match Search","pattern-search"),
    (self.dict["radio-find-type"],"&amp;Script Search","script-search")]
checkLists[0] = [
    ("Scrip&amp;t Change",self.dict["script_change"])]
checkLists[1] = [
    ("&amp;Whole Word",  self.dict["whole_word"]),
    ("&amp;Ignore Case", self.dict["ignore_case"]),
    ("Wrap &amp;Around", self.dict["wrap"]),
    ("&amp;Reverse",     self.dict["reverse"])]
radioLists[2] = [
    (self.dict["radio-search-scope"],"&amp;Entire Outline","entire-outline"),
    (self.dict["radio-search-scope"],"Suboutline &amp;Only","suboutline-only"),  
    (self.dict["radio-search-scope"],"&amp;Node Only","node-only"),
    # I don't know what selection-only is supposed to do.
    (self.dict["radio-search-scope"],"Selection Only",None)] #,"selection-only")]
checkLists[2] = []
checkLists[3] = [
    ("Search &amp;Headline Text", self.dict["search_headline"]),
    ("Search &amp;Body Text",     self.dict["search_body"]),
    ("&amp;Mark Finds",           self.dict["mark_finds"]),
    ("Mark &amp;Changes",         self.dict["mark_changes"])]

for i in xrange(numberOfColumns):
    for var,name,val in radioLists[i]:
        box = underlinedTkButton("radio",columns[i],anchor="w",text=name,variable=var,value=val)
        box.button.pack(fill="x")
        box.button.bind("&lt;1&gt;", self.resetWrap)
        if val == None: box.button.configure(state="disabled")
        box.bindHotKey(ftxt)
        box.bindHotKey(ctxt)
    for name,var in checkLists[i]:
        box = underlinedTkButton("check",columns[i],anchor="w",text=name,variable=var)
        box.button.pack(fill="x")
        box.button.bind("&lt;1&gt;", self.resetWrap)
        box.bindHotKey(ftxt)
        box.bindHotKey(ctxt)
        if var is None: box.button.configure(state="disabled")</t>
<t tx="AGP.20250415230112.3113"># Create the button panes
buttons  = Tk.Frame(outer,bd=1)
buttons2 = Tk.Frame(outer,bd=1)
buttons.pack (anchor="n",expand=1,fill="x")
buttons2.pack(anchor="n",expand=1,fill="x")

# In 4.4 it's dubious to define these keys.  For example, Alt-x must be reserved!
# HotKeys used for check/radio buttons:  a,b,c,e,h,i,l,m,n,o,p,r,s,t,w
# HotKeys used for plain buttons (enter),d,g,t

def findButtonCallback(event=None,self=self):
    self.findButton()
    return 'break'

# Create the first row of buttons
findButton=Tk.Button(buttons,
    width=9,text="Find",bd=4,command=findButtonCallback) # The default.

findButton.pack(pady="1p",padx="25p",side="left")

contextBox = underlinedTkButton("check",buttons,
    anchor="w",text="Show Conte&amp;xt",variable=self.dict["batch"])
contextBox.button.pack(pady="1p",side="left",expand=1)
contextBox.bindHotKey(ftxt)
contextBox.bindHotKey(ctxt)

findAllButton = underlinedTkButton("button",buttons,
    width=9,text="Fin&amp;d All",command=self.findAllButton)
findAllButton.button.pack(pady="1p",padx="25p",side="right",fill="x")
findAllButton.bindHotKey(ftxt)
findAllButton.bindHotKey(ctxt)

# Create the second row of buttons
changeButton = underlinedTkButton("button",buttons2,
    width=10,text="Chan&amp;Ge",command=self.changeButton)
changeButton.button.pack(pady="1p",padx="25p",side="left")
changeButton.bindHotKey(ftxt)
changeButton.bindHotKey(ctxt)

changeFindButton = underlinedTkButton("button",buttons2,
    text="Change, &amp;Then Find",command=self.changeThenFindButton)
changeFindButton.button.pack(pady="1p",side="left",expand=1)
changeFindButton.bindHotKey(ftxt)
changeFindButton.bindHotKey(ctxt)
    
changeAllButton = underlinedTkButton("button",buttons2,
    width=10,text="Change All",command=self.changeAllButton)
changeAllButton.button.pack(pady="1p",padx="25p",side="right")
changeAllButton.bindHotKey(ftxt)
changeAllButton.bindHotKey(ctxt)
</t>
<t tx="AGP.20250415230112.3114">def createBindings (self):
    
    # Legacy bindings.  Can be overwritten in subclasses.
    
    # g.trace('legacy')
    
    def findButtonCallback2(event,self=self):
        self.findButton()
        return 'break'

    for widget in (self.find_ctrl, self.change_ctrl):
        widget.bind ("&lt;Button-1&gt;",  self.resetWrap)
        widget.bind("&lt;Key&gt;",        self.resetWrap)
        widget.bind("&lt;Control-a&gt;",  self.selectAllFindText)
    
    for widget in (self.find_ctrl, self.change_ctrl):
        widget.bind("&lt;Key-Return&gt;", findButtonCallback2)
        widget.bind("&lt;Key-Escape&gt;", self.onCloseWindow)
</t>
<t tx="AGP.20250415230112.3115">def init (self,c):

    # N.B.: separate c.ivars are much more convenient than a dict.
    for key in self.intKeys:
        # New in 4.3: get ivars from @settings.
        val = c.config.getBool(key)
        setattr(self,key,val)
        val = g.choose(val,1,0) # Work around major Tk problem.
        self.dict[key].set(val)
        # g.trace(key,val)

    &lt;&lt; set find/change widgets &gt;&gt;
    &lt;&lt; set radio buttons from ivars &gt;&gt;
</t>
<t tx="AGP.20250415230112.3116">self.find_ctrl.delete("1.0","end")
self.change_ctrl.delete("1.0","end")

# New in 4.3: Get setting from @settings.
for w,setting,defaultText in (
    (self.find_ctrl,"find_text",'&lt;find pattern here&gt;'),
    (self.change_ctrl,"change_text",''),
):
    s = c.config.getString(setting)
    if not s: s = defaultText
    w.insert("end",s)
</t>
<t tx="AGP.20250415230112.3117">found = False
for var,setting in (
    ("pattern_match","pattern-search"),
    ("script_search","script-search")):
    val = self.dict[var].get()
    if val:
        self.dict["radio-find-type"].set(setting)
        found = True ; break
if not found:
    self.dict["radio-find-type"].set("plain-search")
    
found = False
for var,setting in (
    ("suboutline_only","suboutline-only"),
    ("node_only","node-only"),
    # ("selection_only","selection-only"),
):
    val = self.dict[var].get()
    if val:
        self.dict["radio-search-scope"].set(setting)
        found = True ; break
if not found:
    self.dict["radio-search-scope"].set("entire-outline")
</t>
<t tx="AGP.20250415230112.3118">def update_ivars (self):
    
    """Called just before doing a find to update ivars from the find panel."""

    for key in self.intKeys:
        val = self.dict[key].get()
        setattr(self, key, val) # No more _flag hack.
        # g.trace(key,val)

    # Set ivars from radio buttons. Convert these to 1 or 0.
    if 0: ###
        find_type = self.dict["radio-find-type"].get()
        self.pattern_match = g.choose(find_type == "pattern-search",1,0)
        self.script_search = g.choose(find_type == "script-search",1,0)
    
    search_scope = self.dict["radio-search-scope"].get()
    self.suboutline_only = g.choose(search_scope == "suboutline-only",1,0)
    self.node_only       = g.choose(search_scope == "node-only",1,0)
    self.selection       = g.choose(search_scope == "selection-only",1,0) # 11/9/03

    # New in 4.3: The caller is responsible for removing most trailing cruft.
    # Among other things, this allows Leo to search for a single trailing space.
    s = self.find_ctrl.get("1.0","end")
    s = g.toUnicode(s,g.app.tkEncoding)
    # g.trace(repr(s))
    if s and s[-1] in ('\r','\n'):
        s = s[:-1]
    self.find_text = s

    s = self.change_ctrl.get("1.0","end")
    if s and s[-1] in ('\r','\n'):
        s = s[:-1]
    s = g.toUnicode(s,g.app.tkEncoding)
    self.change_text = s
</t>
<t tx="AGP.20250415230112.3119">def adjust_find_text(self,s):
    
    w = self.find_ctrl
    
    w.delete("1.0","end")
    w.insert("end",s)
</t>
<t tx="AGP.20250415230112.3120">def onCloseWindow(self,event=None):
    
    self.top.withdraw()
</t>
<t tx="AGP.20250415230112.3121">def dismiss (self):
    
    self.top.withdraw()
</t>
<t tx="AGP.20250415230112.3122">def bringToFront (self):
    
    """Bring the tkinter Find Panel to the front."""
    
    c = self.c ; t = self.find_ctrl ; gui = g.app.gui
            
    self.top.withdraw() # Helps bring the window to the front.
    self.top.deiconify()
    self.top.lift()

    c.widgetWantsFocusNow(t)
    gui.selectAllText(t)
</t>
<t tx="AGP.20250415230112.3123">def selectAllFindText (self,event=None):

    try:
        w = self.frame.focus_get()
        g.app.gui.setTextSelection(w,"1.0","end")
        return "break"
    except:
        return None # To keep pychecker happy.
</t>
<t tx="AGP.20250415230112.3124">def init_s_ctrl (self,s):
    t = self.s_ctrl
    t.delete("1.0","end")
    t.insert("end",s)
    t.mark_set("insert",g.choose(self.reverse,"end","1.0"))
    return t
</t>
<t tx="AGP.20251113192637"></t>
<t tx="AGP.20251113192637.1">REG ADD HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.leox /f /ve /t REG_SZ /d "LeoxFile"
REG ADD HKEY_LOCAL_MACHINE\SOFTWARE\Classes\LeoxFile /f /ve /t REG_SZ /d "Leox File"
REG ADD HKEY_LOCAL_MACHINE\SOFTWARE\Classes\LeoxFile\DefaultIcon /f /ve /t REG_SZ /d "%~dp0Icons\LeoxDoc.ico"

REG ADD HKEY_LOCAL_MACHINE\SOFTWARE\Classes\LeoxFile\shell /f /ve /t REG_SZ /d "open"
REG ADD HKEY_LOCAL_MACHINE\SOFTWARE\Classes\LeoxFile\shell\open /f /ve /t REG_SZ /d "open"
REG ADD HKEY_LOCAL_MACHINE\SOFTWARE\Classes\LeoxFile\shell\open\command /f /ve /t REG_SZ /d "\"%~dp0Python27win64\python.exe\" \"%~dp0src\leo.py\" \"%%1\""</t>
<t tx="AGP.20251113192710">REG ADD HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.leox /f /ve /t REG_SZ /d "LeoxFile"
REG ADD HKEY_LOCAL_MACHINE\SOFTWARE\Classes\LeoxFile /f /ve /t REG_SZ /d "Leox File"
REG ADD HKEY_LOCAL_MACHINE\SOFTWARE\Classes\LeoxFile\DefaultIcon /f /ve /t REG_SZ /d "%~dp0Icons\LeoxDoc.ico"

REG ADD HKEY_LOCAL_MACHINE\SOFTWARE\Classes\LeoxFile\shell /f /ve /t REG_SZ /d "open"
REG ADD HKEY_LOCAL_MACHINE\SOFTWARE\Classes\LeoxFile\shell\open /f /ve /t REG_SZ /d "open"
REG ADD HKEY_LOCAL_MACHINE\SOFTWARE\Classes\LeoxFile\shell\open\command /f /ve /t REG_SZ /d "\"%~dp0Python27win64\pythonw.exe\" \"%~dp0src\leo.py\" \"%%1\""</t>
<t tx="AGP.20251113192847">REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.leox
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\LeoxFile
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\LeoxFile\DefaultIcon
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\LeoxFile\shell
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\LeoxFile\shell\open
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\LeoxFile\shell\open\command
</t>
</tnodes>
</leo_file>
